### ISSUE TITLE
Windows环境下如何采用VS或Clion的IDE进行调试？

### ISSUE THREAD

**Issue by lyf712** [oceanbase/miniob#100]
## 问题描述
学Java比较多，对于C\C++的开发环境还不太熟悉；看了Doc文档，所提供的how_to_build_by_vs是MAC或Linux环境的进行开发吧？不支持Win的吧？我采用Clion进行调试会**找不到sys\call.h头文件**，这类文件windows环境下无该库文件。而Window推荐采用docker开发，那是不是不方便进行调试启动啊？
![image](https://user-images.githubusercontent.com/62736461/195555411-36b300b2-476d-4ded-a283-22bbd8c19462.png)
## 诉求
如果用的windows电脑大家有什么好办法去解决IDE环境下调试该源代码的办法吗（虚拟机里面调试吗）

**Comment by hnwyllmm** [comment]
https://github.com/oceanbase/miniob/pull/125
