### ISSUE TITLE
编译后没有miniob.sock文件

### ISSUE THREAD

**Issue by 1014809521** [oceanbase/miniob#110]
使用docker镜像运行build.sh后未发现miniob.sock文件

**Comment by hnwyllmm** [comment]
miniob.sock 是一个unix socket 文件，不是编译生成的，是在运行时生成的。
比如在编译后，build 目录中执行：
./bin/observer -s miniob.sock -f ../etc/observer.ini
启动observer后会自动生成miniob.sock，obclient可以通过这个文件与observer通讯。
同学有兴趣的话，可以网上搜索一下unix socket。
另外，这个文件名字是可以自行指定的，不一定叫miniob.sock。

**Comment by 1014809521** [comment]
好的好的，非常感谢您的指导
