### ISSUE TITLE
[Feature Request] 命令行客户端增强

### ISSUE THREAD

**Issue by StLeoX** [oceanbase/miniob#113]
命令行客户端增强：
- 可编辑行缓冲：当前输入是单字符缓冲的，希望实现行缓冲，具体包括：
  - 能左、右移动字符；
  - 能移动到行首、行位；
  - 能中途截断（取消）行；
- 历史记录缓冲：目前未实现历史记录，期望：
  - 能上下切换历史命令；
  - 能支持子串查询；

**Comment by StLeoX** [comment]
ref: https://blog.csdn.net/zgcjaxj/article/details/114548681

**Comment by imdouyu** [comment]
可以了解一下rlwrap，以`rlwrap ./obclient`运行客户端，你提到的功能都可以实现
