### ISSUE TITLE
 Rewrite the thread pool

### ISSUE THREAD

**Issue by longdafeng** [oceanbase/miniob#138]
当前seda 架构是一种适合无状态event 驱动的线程池模型, 

但在数据库当中是有状态线程池模型, 举例来说, 一个session 内的所有command 应该都在这个session 的上下文操作当中, 并且需要保持在这个session内部有序执行, 因此线程和session 某种意义上是有关联的, 另外在磁盘io 同样需要保证某些事物的有序执行, 另外对同一个文件的操作建议归并到单线程去执行io, 避免写冲突.

**Comment by hnwyllmm** [comment]
seda中有一个线程池可以重用，把那个thread_pool中的schedule关于stage的操作，再抽象一层出来就可以。

**Comment by hnwyllmm** [comment]
线程池的实现还可以参考 mariadb
https://mariadb.com/kb/en/thread-groups-in-the-unix-implementation-of-the-thread-pool/

**Comment by hnwyllmm** [comment]
新的线程池实现之后，可以把test.yml中sysbench-test打开

**Comment by hnwyllmm** [comment]
closed by #332
