### ISSUE TITLE
gitpod support

### ISSUE THREAD

**Issue by hnwyllmm** [oceanbase/miniob#146]
**Is your feature request related to a problem? Please describe.**
[gitpod](https://www.gitpod.io/) 是一个云开发工具，可以直接在任何设备上，登录自己的账号就开始自己的编码。
可以支持浏览器、vscode等终端工具，非常方便。

gitpod也可以直接开发miniob，但是miniob有一些依赖库，需要在环境初始化时，安装这些依赖库。可以在miniob github项目中增加一些配置文件，告诉gitpod初始化时做什么。

**Describe the solution you'd like**

最简单的初始化gitpod环境的方法就是增加配置文件，执行bash build.sh init。

**Describe alternatives you've considered**

**Additional context**

可以参考 [ob-example/.gitpod.yaml](https://github.com/oceanbase/ob-example/blob/master/.gitpod.yml)

**Comment by gitccl** [comment]
Hi, I'd like to do this task.

**Comment by hnwyllmm** [comment]
Great! Thanks!发自我的 iPhone在 2023年4月1日，22:04，gitccl ***@***.***> 写道：﻿
Hi, I'd like to do this task.
