### ISSUE TITLE
Could not find a package configuration file provided by "benchmark" with   any of the following names: [BUG]

### ISSUE THREAD

**Issue by songmuhan** [oceanbase/miniob#154]
**Describe the bug**
根据文档中的步骤编译，在构建moniob时出现了错误

** Environment**
- OS Version: mac
- CPU Arch(x86/arm): m2
- Compiler:  Apple clang version 14.0.0 (clang-1400.0.29.202)
- Others:

**Fast Reproduce Steps(Required)**
按照how_to_build的教程走，当编译miniob时报错
```
mkdir build
cmake .. -DEBUG=on
```
**Actual Behavior**
```
-- This is SOURCE dir /Users/a1/Public/miniob/test/perf
-- This is BINARY dir /Users/a1/Public/miniob/build/test/perf
-- This is Project source dir /Users/a1/Public/miniob
-- This is PROJECT_BINARY_DIR dir /Users/a1/Public/miniob/build
-- HOME dir: /Users/a1
-- This is apple
DEBUG has been set as TRUE ON
CMAKE_CXX_FLAGS is  -Wall -DCMAKE_EXPORT_COMPILE_COMMANDS=1  -O0 -g -DDEBUG 
CMAKE_INSTALL_PREFIX has been set as /usr/local
Install target dir is /usr/local
Begin to build common
-- This is PROJECT_BINARY_DIR dir /Users/a1/Public/miniob/build/deps/common
-- This is PROJECT_SOURCE_DIR dir /Users/a1/Public/miniob/deps/common
Use /Users/a1/Public/miniob/deps/common/conf/ini.cpp
Use /Users/a1/Public/miniob/deps/common/io/io.cpp
Use /Users/a1/Public/miniob/deps/common/io/roll_select_dir.cpp
Use /Users/a1/Public/miniob/deps/common/lang/bitmap.cpp
Use /Users/a1/Public/miniob/deps/common/lang/comparator.cpp
Use /Users/a1/Public/miniob/deps/common/lang/mutex.cpp
Use /Users/a1/Public/miniob/deps/common/lang/string.cpp
Use /Users/a1/Public/miniob/deps/common/log/log.cpp
Use /Users/a1/Public/miniob/deps/common/math/md5.cpp
Use /Users/a1/Public/miniob/deps/common/math/random_generator.cpp
Use /Users/a1/Public/miniob/deps/common/math/regex.cpp
Use /Users/a1/Public/miniob/deps/common/metrics/console_reporter.cpp
Use /Users/a1/Public/miniob/deps/common/metrics/histogram_snapshot.cpp
Use /Users/a1/Public/miniob/deps/common/metrics/log_reporter.cpp
Use /Users/a1/Public/miniob/deps/common/metrics/metrics.cpp
Use /Users/a1/Public/miniob/deps/common/metrics/metrics_registry.cpp
Use /Users/a1/Public/miniob/deps/common/metrics/reporter.cpp
Use /Users/a1/Public/miniob/deps/common/metrics/reservoir.cpp
Use /Users/a1/Public/miniob/deps/common/metrics/sampler.cpp
Use /Users/a1/Public/miniob/deps/common/metrics/timer_snapshot.cpp
Use /Users/a1/Public/miniob/deps/common/metrics/uniform_reservoir.cpp
Use /Users/a1/Public/miniob/deps/common/mm/mem_pool.cpp
Use /Users/a1/Public/miniob/deps/common/os/os.cpp
Use /Users/a1/Public/miniob/deps/common/os/path.cpp
Use /Users/a1/Public/miniob/deps/common/os/pidfile.cpp
Use /Users/a1/Public/miniob/deps/common/os/process.cpp
Use /Users/a1/Public/miniob/deps/common/os/process_param.cpp
Use /Users/a1/Public/miniob/deps/common/os/signal.cpp
Use /Users/a1/Public/miniob/deps/common/seda/callback.cpp
Use /Users/a1/Public/miniob/deps/common/seda/event_dispatcher.cpp
Use /Users/a1/Public/miniob/deps/common/seda/example_stage.cpp
Use /Users/a1/Public/miniob/deps/common/seda/init.cpp
Use /Users/a1/Public/miniob/deps/common/seda/kill_thread.cpp
Use /Users/a1/Public/miniob/deps/common/seda/metrics_report_event.cpp
Use /Users/a1/Public/miniob/deps/common/seda/metrics_stage.cpp
Use /Users/a1/Public/miniob/deps/common/seda/seda_config.cpp
Use /Users/a1/Public/miniob/deps/common/seda/stage.cpp
Use /Users/a1/Public/miniob/deps/common/seda/stage_event.cpp
Use /Users/a1/Public/miniob/deps/common/seda/thread_pool.cpp
Use /Users/a1/Public/miniob/deps/common/seda/timer_stage.cpp
Use /Users/a1/Public/miniob/deps/common/time/datetime.cpp
Use /Users/a1/Public/miniob/deps/common/time/timeout_info.cpp
-- This is the func_static OUTPUT_NAME:common
Install conf/ini.h to /usr/local/common/include/conf
Install defs.h to /usr/local/common/include/
Install io/io.h to /usr/local/common/include/io
Install io/roll_select_dir.h to /usr/local/common/include/io
Install io/select_dir.h to /usr/local/common/include/io
Install lang/bitmap.h to /usr/local/common/include/lang
Install lang/comparator.h to /usr/local/common/include/lang
Install lang/defer.h to /usr/local/common/include/lang
Install lang/lower_bound.h to /usr/local/common/include/lang
Install lang/lru_cache.h to /usr/local/common/include/lang
Install lang/mutex.h to /usr/local/common/include/lang
Install lang/serializable.h to /usr/local/common/include/lang
Install lang/string.h to /usr/local/common/include/lang
Install log/log.h to /usr/local/common/include/log
Install math/md5.h to /usr/local/common/include/math
Install math/random_generator.h to /usr/local/common/include/math
Install math/regex.h to /usr/local/common/include/math
Install metrics/console_reporter.h to /usr/local/common/include/metrics
Install metrics/histogram_snapshot.h to /usr/local/common/include/metrics
Install metrics/log_reporter.h to /usr/local/common/include/metrics
Install metrics/metric.h to /usr/local/common/include/metrics
Install metrics/metrics.h to /usr/local/common/include/metrics
Install metrics/metrics_registry.h to /usr/local/common/include/metrics
Install metrics/reporter.h to /usr/local/common/include/metrics
Install metrics/reservoir.h to /usr/local/common/include/metrics
Install metrics/sampler.h to /usr/local/common/include/metrics
Install metrics/snapshot.h to /usr/local/common/include/metrics
Install metrics/timer_snapshot.h to /usr/local/common/include/metrics
Install metrics/uniform_reservoir.h to /usr/local/common/include/metrics
Install mm/debug_new.h to /usr/local/common/include/mm
Install mm/mem.h to /usr/local/common/include/mm
Install mm/mem_pool.h to /usr/local/common/include/mm
Install os/os.h to /usr/local/common/include/os
Install os/path.h to /usr/local/common/include/os
Install os/pidfile.h to /usr/local/common/include/os
Install os/process.h to /usr/local/common/include/os
Install os/process_param.h to /usr/local/common/include/os
Install os/signal.h to /usr/local/common/include/os
Install seda/callback.h to /usr/local/common/include/seda
Install seda/class_factory.h to /usr/local/common/include/seda
Install seda/event_dispatcher.h to /usr/local/common/include/seda
Install seda/example_stage.h to /usr/local/common/include/seda
Install seda/init.h to /usr/local/common/include/seda
Install seda/kill_thread.h to /usr/local/common/include/seda
Install seda/metrics_report_event.h to /usr/local/common/include/seda
Install seda/metrics_stage.h to /usr/local/common/include/seda
Install seda/seda_config.h to /usr/local/common/include/seda
Install seda/seda_defs.h to /usr/local/common/include/seda
Install seda/stage.h to /usr/local/common/include/seda
Install seda/stage_event.h to /usr/local/common/include/seda
Install seda/stage_factory.h to /usr/local/common/include/seda
Install seda/thread_pool.h to /usr/local/common/include/seda
Install seda/timer_stage.h to /usr/local/common/include/seda
Install time/datetime.h to /usr/local/common/include/time
Install time/timeout_info.h to /usr/local/common/include/time
Install version.h to /usr/local/common/include/
Begin to build miniob
-- This is PROJECT_BINARY_DIR dir /Users/a1/Public/miniob/build/src
-- This is PROJECT_SOURCE_DIR dir /Users/a1/Public/miniob/src
Begin to build obclient
Use /Users/a1/Public/miniob/src/obclient/client.cpp
Binary directory:/Users/a1/Public/miniob/build/src/../bin
Begin to build observer
-- This is PROJECT_BINARY_DIR dir /Users/a1/Public/miniob/build/src/observer
-- This is PROJECT_SOURCE_DIR dir /Users/a1/Public/miniob/src/observer
MAIN SRC: /Users/a1/Public/miniob/src/observer/main.cpp
Use /Users/a1/Public/miniob/src/observer/event/session_event.cpp
Use /Users/a1/Public/miniob/src/observer/event/sql_event.cpp
Use /Users/a1/Public/miniob/src/observer/init.cpp
Use /Users/a1/Public/miniob/src/observer/main.cpp
Use /Users/a1/Public/miniob/src/observer/net/communicator.cpp
Use /Users/a1/Public/miniob/src/observer/net/mysql_communicator.cpp
Use /Users/a1/Public/miniob/src/observer/net/server.cpp
Use /Users/a1/Public/miniob/src/observer/rc.cpp
Use /Users/a1/Public/miniob/src/observer/session/session.cpp
Use /Users/a1/Public/miniob/src/observer/session/session_stage.cpp
Use /Users/a1/Public/miniob/src/observer/session/thread_data.cpp
Use /Users/a1/Public/miniob/src/observer/sql/executor/execute_stage.cpp
Use /Users/a1/Public/miniob/src/observer/sql/executor/sql_result.cpp
Use /Users/a1/Public/miniob/src/observer/sql/expr/expression.cpp
Use /Users/a1/Public/miniob/src/observer/sql/expr/tuple_cell.cpp
Use /Users/a1/Public/miniob/src/observer/sql/operator/delete_logical_operator.cpp
Use /Users/a1/Public/miniob/src/observer/sql/operator/delete_physical_operator.cpp
Use /Users/a1/Public/miniob/src/observer/sql/operator/explain_physical_operator.cpp
Use /Users/a1/Public/miniob/src/observer/sql/operator/index_scan_physical_operator.cpp
Use /Users/a1/Public/miniob/src/observer/sql/operator/insert_physical_operator.cpp
Use /Users/a1/Public/miniob/src/observer/sql/operator/join_physical_operator.cpp
Use /Users/a1/Public/miniob/src/observer/sql/operator/logical_operator.cpp
Use /Users/a1/Public/miniob/src/observer/sql/operator/physical_operator.cpp
Use /Users/a1/Public/miniob/src/observer/sql/operator/predicate_logical_operator.cpp
Use /Users/a1/Public/miniob/src/observer/sql/operator/predicate_physical_operator.cpp
Use /Users/a1/Public/miniob/src/observer/sql/operator/project_logical_operator.cpp
Use /Users/a1/Public/miniob/src/observer/sql/operator/project_physical_operator.cpp
Use /Users/a1/Public/miniob/src/observer/sql/operator/table_get_logical_operator.cpp
Use /Users/a1/Public/miniob/src/observer/sql/operator/table_scan_physical_operator.cpp
Use /Users/a1/Public/miniob/src/observer/sql/optimizer/comparison_simplification_rule.cpp
Use /Users/a1/Public/miniob/src/observer/sql/optimizer/conjunction_simplification_rule.cpp
Use /Users/a1/Public/miniob/src/observer/sql/optimizer/expression_rewriter.cpp
Use /Users/a1/Public/miniob/src/observer/sql/optimizer/optimize_stage.cpp
Use /Users/a1/Public/miniob/src/observer/sql/optimizer/physical_plan_generator.cpp
Use /Users/a1/Public/miniob/src/observer/sql/optimizer/predicate_pushdown_rewriter.cpp
Use /Users/a1/Public/miniob/src/observer/sql/optimizer/predicate_rewrite.cpp
Use /Users/a1/Public/miniob/src/observer/sql/optimizer/rewriter.cpp
Use /Users/a1/Public/miniob/src/observer/sql/parser/lex_sql.cpp
Use /Users/a1/Public/miniob/src/observer/sql/parser/parse.cpp
Use /Users/a1/Public/miniob/src/observer/sql/parser/parse_stage.cpp
Use /Users/a1/Public/miniob/src/observer/sql/parser/resolve_stage.cpp
Use /Users/a1/Public/miniob/src/observer/sql/parser/yacc_sql.cpp
Use /Users/a1/Public/miniob/src/observer/sql/plan_cache/plan_cache_stage.cpp
Use /Users/a1/Public/miniob/src/observer/sql/query_cache/query_cache_stage.cpp
Use /Users/a1/Public/miniob/src/observer/sql/stmt/delete_stmt.cpp
Use /Users/a1/Public/miniob/src/observer/sql/stmt/explain_stmt.cpp
Use /Users/a1/Public/miniob/src/observer/sql/stmt/filter_stmt.cpp
Use /Users/a1/Public/miniob/src/observer/sql/stmt/insert_stmt.cpp
Use /Users/a1/Public/miniob/src/observer/sql/stmt/select_stmt.cpp
Use /Users/a1/Public/miniob/src/observer/sql/stmt/stmt.cpp
Use /Users/a1/Public/miniob/src/observer/sql/stmt/update_stmt.cpp
Use /Users/a1/Public/miniob/src/observer/storage/buffer/frame.cpp
Use /Users/a1/Public/miniob/src/observer/storage/clog/clog.cpp
Use /Users/a1/Public/miniob/src/observer/storage/common/condition_filter.cpp
Use /Users/a1/Public/miniob/src/observer/storage/common/db.cpp
Use /Users/a1/Public/miniob/src/observer/storage/common/field_meta.cpp
Use /Users/a1/Public/miniob/src/observer/storage/common/index_meta.cpp
Use /Users/a1/Public/miniob/src/observer/storage/common/meta_util.cpp
Use /Users/a1/Public/miniob/src/observer/storage/common/table.cpp
Use /Users/a1/Public/miniob/src/observer/storage/common/table_meta.cpp
Use /Users/a1/Public/miniob/src/observer/storage/default/default_handler.cpp
Use /Users/a1/Public/miniob/src/observer/storage/default/default_storage_stage.cpp
Use /Users/a1/Public/miniob/src/observer/storage/default/disk_buffer_pool.cpp
Use /Users/a1/Public/miniob/src/observer/storage/index/bplus_tree.cpp
Use /Users/a1/Public/miniob/src/observer/storage/index/bplus_tree_index.cpp
Use /Users/a1/Public/miniob/src/observer/storage/index/index.cpp
Use /Users/a1/Public/miniob/src/observer/storage/mem/mem_storage_stage.cpp
Use /Users/a1/Public/miniob/src/observer/storage/persist/persist.cpp
Use /Users/a1/Public/miniob/src/observer/storage/record/record_manager.cpp
Use /Users/a1/Public/miniob/src/observer/storage/trx/latch_memo.cpp
Use /Users/a1/Public/miniob/src/observer/storage/trx/trx.cpp
Binary directory:/Users/a1/Public/miniob/build/src/observer/../../bin
Archive directory:/Users/a1/Public/miniob/build/src/observer/../../lib
Begin to build test
-- This is PROJECT_BINARY_DIR dir /Users/a1/Public/miniob/build/test/perf
-- This is PROJECT_SOURCE_DIR dir /Users/a1/Public/miniob/test/perf
 -Wall -DCMAKE_EXPORT_COMPILE_COMMANDS=1  -O0 -g -DDEBUG 
Build client_performance_test according to /Users/a1/Public/miniob/test/perf/client_performance_test.cpp
Begin to build benchmark
-- This is PROJECT_BINARY_DIR dir /Users/a1/Public/miniob/build/benchmark
-- This is PROJECT_SOURCE_DIR dir /Users/a1/Public/miniob/benchmark
 -Wall -DCMAKE_EXPORT_COMPILE_COMMANDS=1  -O0 -g -DDEBUG 
CMake Error at benchmark/CMakeLists.txt:25 (find_package):
  Could not find a package configuration file provided by "benchmark" with
  any of the following names:

    benchmarkConfig.cmake
    benchmark-config.cmake

  Add the installation prefix of "benchmark" to CMAKE_PREFIX_PATH or set
  "benchmark_DIR" to a directory containing one of the above files.  If
  "benchmark" provides a separate development package or SDK, be sure it has
  been installed.


```

**Comment by hnwyllmm** [comment]
主分支，正在开发，文档没有同步更新，非常抱歉。主分支可以直接执行 bash build.sh init 然后在build 或build_debug 目录执行make编译即可在 2023年5月2日，22:20，FkArch ***@***.***> 写道：﻿
Describe the bug
根据文档中的步骤编译，在构建moniob时出现了错误
** Environment**

OS Version: mac
CPU Arch(x86/arm): m2
Compiler:  Apple clang version 14.0.0 (clang-1400.0.29.202)
Others:

Fast Reproduce Steps(Required)
按照how_to_build的教程走，当编译miniob时报错
mkdir build
cmake .. -DEBUG=on

Actual Behavior
-- This is SOURCE dir /Users/a1/Public/miniob/test/perf
-- This is BINARY dir /Users/a1/Public/miniob/build/test/perf
-- This is Project source dir /Users/a1/Public/miniob
-- This is PROJECT_BINARY_DIR dir /Users/a1/Public/miniob/build
-- HOME dir: /Users/a1
-- This is apple
DEBUG has been set as TRUE ON
CMAKE_CXX_FLAGS is  -Wall -DCMAKE_EXPORT_COMPILE_COMMANDS=1  -O0 -g -DDEBUG 
CMAKE_INSTALL_PREFIX has been set as /usr/local
Install target dir is /usr/local
Begin to build common
-- This is PROJECT_BINARY_DIR dir /Users/a1/Public/miniob/build/deps/common
-- This is PROJECT_SOURCE_DIR dir /Users/a1/Public/miniob/deps/common
Use /Users/a1/Public/miniob/deps/common/conf/ini.cpp
Use /Users/a1/Public/miniob/deps/common/io/io.cpp
Use /Users/a1/Public/miniob/deps/common/io/roll_select_dir.cpp
Use /Users/a1/Public/miniob/deps/common/lang/bitmap.cpp
Use /Users/a1/Public/miniob/deps/common/lang/comparator.cpp
Use /Users/a1/Public/miniob/deps/common/lang/mutex.cpp
Use /Users/a1/Public/miniob/deps/common/lang/string.cpp
Use /Users/a1/Public/miniob/deps/common/log/log.cpp
Use /Users/a1/Public/miniob/deps/common/math/md5.cpp
Use /Users/a1/Public/miniob/deps/common/math/random_generator.cpp
Use /Users/a1/Public/miniob/deps/common/math/regex.cpp
Use /Users/a1/Public/miniob/deps/common/metrics/console_reporter.cpp
Use /Users/a1/Public/miniob/deps/common/metrics/histogram_snapshot.cpp
Use /Users/a1/Public/miniob/deps/common/metrics/log_reporter.cpp
Use /Users/a1/Public/miniob/deps/common/metrics/metrics.cpp
Use /Users/a1/Public/miniob/deps/common/metrics/metrics_registry.cpp
Use /Users/a1/Public/miniob/deps/common/metrics/reporter.cpp
Use /Users/a1/Public/miniob/deps/common/metrics/reservoir.cpp
Use /Users/a1/Public/miniob/deps/common/metrics/sampler.cpp
Use /Users/a1/Public/miniob/deps/common/metrics/timer_snapshot.cpp
Use /Users/a1/Public/miniob/deps/common/metrics/uniform_reservoir.cpp
Use /Users/a1/Public/miniob/deps/common/mm/mem_pool.cpp
Use /Users/a1/Public/miniob/deps/common/os/os.cpp
Use /Users/a1/Public/miniob/deps/common/os/path.cpp
Use /Users/a1/Public/miniob/deps/common/os/pidfile.cpp
Use /Users/a1/Public/miniob/deps/common/os/process.cpp
Use /Users/a1/Public/miniob/deps/common/os/process_param.cpp
Use /Users/a1/Public/miniob/deps/common/os/signal.cpp
Use /Users/a1/Public/miniob/deps/common/seda/callback.cpp
Use /Users/a1/Public/miniob/deps/common/seda/event_dispatcher.cpp
Use /Users/a1/Public/miniob/deps/common/seda/example_stage.cpp
Use /Users/a1/Public/miniob/deps/common/seda/init.cpp
Use /Users/a1/Public/miniob/deps/common/seda/kill_thread.cpp
Use /Users/a1/Public/miniob/deps/common/seda/metrics_report_event.cpp
Use /Users/a1/Public/miniob/deps/common/seda/metrics_stage.cpp
Use /Users/a1/Public/miniob/deps/common/seda/seda_config.cpp
Use /Users/a1/Public/miniob/deps/common/seda/stage.cpp
Use /Users/a1/Public/miniob/deps/common/seda/stage_event.cpp
Use /Users/a1/Public/miniob/deps/common/seda/thread_pool.cpp
Use /Users/a1/Public/miniob/deps/common/seda/timer_stage.cpp
Use /Users/a1/Public/miniob/deps/common/time/datetime.cpp
Use /Users/a1/Public/miniob/deps/common/time/timeout_info.cpp
-- This is the func_static OUTPUT_NAME:common
Install conf/ini.h to /usr/local/common/include/conf
Install defs.h to /usr/local/common/include/
Install io/io.h to /usr/local/common/include/io
Install io/roll_select_dir.h to /usr/local/common/include/io
Install io/select_dir.h to /usr/local/common/include/io
Install lang/bitmap.h to /usr/local/common/include/lang
Install lang/comparator.h to /usr/local/common/include/lang
Install lang/defer.h to /usr/local/common/include/lang
Install lang/lower_bound.h to /usr/local/common/include/lang
Install lang/lru_cache.h to /usr/local/common/include/lang
Install lang/mutex.h to /usr/local/common/include/lang
Install lang/serializable.h to /usr/local/common/include/lang
Install lang/string.h to /usr/local/common/include/lang
Install log/log.h to /usr/local/common/include/log
Install math/md5.h to /usr/local/common/include/math
Install math/random_generator.h to /usr/local/common/include/math
Install math/regex.h to /usr/local/common/include/math
Install metrics/console_reporter.h to /usr/local/common/include/metrics
Install metrics/histogram_snapshot.h to /usr/local/common/include/metrics
Install metrics/log_reporter.h to /usr/local/common/include/metrics
Install metrics/metric.h to /usr/local/common/include/metrics
Install metrics/metrics.h to /usr/local/common/include/metrics
Install metrics/metrics_registry.h to /usr/local/common/include/metrics
Install metrics/reporter.h to /usr/local/common/include/metrics
Install metrics/reservoir.h to /usr/local/common/include/metrics
Install metrics/sampler.h to /usr/local/common/include/metrics
Install metrics/snapshot.h to /usr/local/common/include/metrics
Install metrics/timer_snapshot.h to /usr/local/common/include/metrics
Install metrics/uniform_reservoir.h to /usr/local/common/include/metrics
Install mm/debug_new.h to /usr/local/common/include/mm
Install mm/mem.h to /usr/local/common/include/mm
Install mm/mem_pool.h to /usr/local/common/include/mm
Install os/os.h to /usr/local/common/include/os
Install os/path.h to /usr/local/common/include/os
Install os/pidfile.h to /usr/local/common/include/os
Install os/process.h to /usr/local/common/include/os
Install os/process_param.h to /usr/local/common/include/os
Install os/signal.h to /usr/local/common/include/os
Install seda/callback.h to /usr/local/common/include/seda
Install seda/class_factory.h to /usr/local/common/include/seda
Install seda/event_dispatcher.h to /usr/local/common/include/seda
Install seda/example_stage.h to /usr/local/common/include/seda
Install seda/init.h to /usr/local/common/include/seda
Install seda/kill_thread.h to /usr/local/common/include/seda
Install seda/metrics_report_event.h to /usr/local/common/include/seda
Install seda/metrics_stage.h to /usr/local/common/include/seda
Install seda/seda_config.h to /usr/local/common/include/seda
Install seda/seda_defs.h to /usr/local/common/include/seda
Install seda/stage.h to /usr/local/common/include/seda
Install seda/stage_event.h to /usr/local/common/include/seda
Install seda/stage_factory.h to /usr/local/common/include/seda
Install seda/thread_pool.h to /usr/local/common/include/seda
Install seda/timer_stage.h to /usr/local/common/include/seda
Install time/datetime.h to /usr/local/common/include/time
Install time/timeout_info.h to /usr/local/common/include/time
Install version.h to /usr/local/common/include/
Begin to build miniob
-- This is PROJECT_BINARY_DIR dir /Users/a1/Public/miniob/build/src
-- This is PROJECT_SOURCE_DIR dir /Users/a1/Public/miniob/src
Begin to build obclient
Use /Users/a1/Public/miniob/src/obclient/client.cpp
Binary directory:/Users/a1/Public/miniob/build/src/../bin
Begin to build observer
-- This is PROJECT_BINARY_DIR dir /Users/a1/Public/miniob/build/src/observer
-- This is PROJECT_SOURCE_DIR dir /Users/a1/Public/miniob/src/observer
MAIN SRC: /Users/a1/Public/miniob/src/observer/main.cpp
Use /Users/a1/Public/miniob/src/observer/event/session_event.cpp
Use /Users/a1/Public/miniob/src/observer/event/sql_event.cpp
Use /Users/a1/Public/miniob/src/observer/init.cpp
Use /Users/a1/Public/miniob/src/observer/main.cpp
Use /Users/a1/Public/miniob/src/observer/net/communicator.cpp
Use /Users/a1/Public/miniob/src/observer/net/mysql_communicator.cpp
Use /Users/a1/Public/miniob/src/observer/net/server.cpp
Use /Users/a1/Public/miniob/src/observer/rc.cpp
Use /Users/a1/Public/miniob/src/observer/session/session.cpp
Use /Users/a1/Public/miniob/src/observer/session/session_stage.cpp
Use /Users/a1/Public/miniob/src/observer/session/thread_data.cpp
Use /Users/a1/Public/miniob/src/observer/sql/executor/execute_stage.cpp
Use /Users/a1/Public/miniob/src/observer/sql/executor/sql_result.cpp
Use /Users/a1/Public/miniob/src/observer/sql/expr/expression.cpp
Use /Users/a1/Public/miniob/src/observer/sql/expr/tuple_cell.cpp
Use /Users/a1/Public/miniob/src/observer/sql/operator/delete_logical_operator.cpp
Use /Users/a1/Public/miniob/src/observer/sql/operator/delete_physical_operator.cpp
Use /Users/a1/Public/miniob/src/observer/sql/operator/explain_physical_operator.cpp
Use /Users/a1/Public/miniob/src/observer/sql/operator/index_scan_physical_operator.cpp
Use /Users/a1/Public/miniob/src/observer/sql/operator/insert_physical_operator.cpp
Use /Users/a1/Public/miniob/src/observer/sql/operator/join_physical_operator.cpp
Use /Users/a1/Public/miniob/src/observer/sql/operator/logical_operator.cpp
Use /Users/a1/Public/miniob/src/observer/sql/operator/physical_operator.cpp
Use /Users/a1/Public/miniob/src/observer/sql/operator/predicate_logical_operator.cpp
Use /Users/a1/Public/miniob/src/observer/sql/operator/predicate_physical_operator.cpp
Use /Users/a1/Public/miniob/src/observer/sql/operator/project_logical_operator.cpp
Use /Users/a1/Public/miniob/src/observer/sql/operator/project_physical_operator.cpp
Use /Users/a1/Public/miniob/src/observer/sql/operator/table_get_logical_operator.cpp
Use /Users/a1/Public/miniob/src/observer/sql/operator/table_scan_physical_operator.cpp
Use /Users/a1/Public/miniob/src/observer/sql/optimizer/comparison_simplification_rule.cpp
Use /Users/a1/Public/miniob/src/observer/sql/optimizer/conjunction_simplification_rule.cpp
Use /Users/a1/Public/miniob/src/observer/sql/optimizer/expression_rewriter.cpp
Use /Users/a1/Public/miniob/src/observer/sql/optimizer/optimize_stage.cpp
Use /Users/a1/Public/miniob/src/observer/sql/optimizer/physical_plan_generator.cpp
Use /Users/a1/Public/miniob/src/observer/sql/optimizer/predicate_pushdown_rewriter.cpp
Use /Users/a1/Public/miniob/src/observer/sql/optimizer/predicate_rewrite.cpp
Use /Users/a1/Public/miniob/src/observer/sql/optimizer/rewriter.cpp
Use /Users/a1/Public/miniob/src/observer/sql/parser/lex_sql.cpp
Use /Users/a1/Public/miniob/src/observer/sql/parser/parse.cpp
Use /Users/a1/Public/miniob/src/observer/sql/parser/parse_stage.cpp
Use /Users/a1/Public/miniob/src/observer/sql/parser/resolve_stage.cpp
Use /Users/a1/Public/miniob/src/observer/sql/parser/yacc_sql.cpp
Use /Users/a1/Public/miniob/src/observer/sql/plan_cache/plan_cache_stage.cpp
Use /Users/a1/Public/miniob/src/observer/sql/query_cache/query_cache_stage.cpp
Use /Users/a1/Public/miniob/src/observer/sql/stmt/delete_stmt.cpp
Use /Users/a1/Public/miniob/src/observer/sql/stmt/explain_stmt.cpp
Use /Users/a1/Public/miniob/src/observer/sql/stmt/filter_stmt.cpp
Use /Users/a1/Public/miniob/src/observer/sql/stmt/insert_stmt.cpp
Use /Users/a1/Public/miniob/src/observer/sql/stmt/select_stmt.cpp
Use /Users/a1/Public/miniob/src/observer/sql/stmt/stmt.cpp
Use /Users/a1/Public/miniob/src/observer/sql/stmt/update_stmt.cpp
Use /Users/a1/Public/miniob/src/observer/storage/buffer/frame.cpp
Use /Users/a1/Public/miniob/src/observer/storage/clog/clog.cpp
Use /Users/a1/Public/miniob/src/observer/storage/common/condition_filter.cpp
Use /Users/a1/Public/miniob/src/observer/storage/common/db.cpp
Use /Users/a1/Public/miniob/src/observer/storage/common/field_meta.cpp
Use /Users/a1/Public/miniob/src/observer/storage/common/index_meta.cpp
Use /Users/a1/Public/miniob/src/observer/storage/common/meta_util.cpp
Use /Users/a1/Public/miniob/src/observer/storage/common/table.cpp
Use /Users/a1/Public/miniob/src/observer/storage/common/table_meta.cpp
Use /Users/a1/Public/miniob/src/observer/storage/default/default_handler.cpp
Use /Users/a1/Public/miniob/src/observer/storage/default/default_storage_stage.cpp
Use /Users/a1/Public/miniob/src/observer/storage/default/disk_buffer_pool.cpp
Use /Users/a1/Public/miniob/src/observer/storage/index/bplus_tree.cpp
Use /Users/a1/Public/miniob/src/observer/storage/index/bplus_tree_index.cpp
Use /Users/a1/Public/miniob/src/observer/storage/index/index.cpp
Use /Users/a1/Public/miniob/src/observer/storage/mem/mem_storage_stage.cpp
Use /Users/a1/Public/miniob/src/observer/storage/persist/persist.cpp
Use /Users/a1/Public/miniob/src/observer/storage/record/record_manager.cpp
Use /Users/a1/Public/miniob/src/observer/storage/trx/latch_memo.cpp
Use /Users/a1/Public/miniob/src/observer/storage/trx/trx.cpp
Binary directory:/Users/a1/Public/miniob/build/src/observer/../../bin
Archive directory:/Users/a1/Public/miniob/build/src/observer/../../lib
Begin to build test
-- This is PROJECT_BINARY_DIR dir /Users/a1/Public/miniob/build/test/perf
-- This is PROJECT_SOURCE_DIR dir /Users/a1/Public/miniob/test/perf
 -Wall -DCMAKE_EXPORT_COMPILE_COMMANDS=1  -O0 -g -DDEBUG 
Build client_performance_test according to /Users/a1/Public/miniob/test/perf/client_performance_test.cpp
Begin to build benchmark
-- This is PROJECT_BINARY_DIR dir /Users/a1/Public/miniob/build/benchmark
-- This is PROJECT_SOURCE_DIR dir /Users/a1/Public/miniob/benchmark
 -Wall -DCMAKE_EXPORT_COMPILE_COMMANDS=1  -O0 -g -DDEBUG 
CMake Error at benchmark/CMakeLists.txt:25 (find_package):
  Could not find a package configuration file provided by "benchmark" with
  any of the following names:

    benchmarkConfig.cmake
    benchmark-config.cmake

  Add the installation prefix of "benchmark" to CMAKE_PREFIX_PATH or set
  "benchmark_DIR" to a directory containing one of the above files.  If
  "benchmark" provides a separate development package or SDK, be sure it has
  been installed.

**Comment by hnwyllmm** [comment]
> ？咋改的，我用新弄出来的bash build.sh 在wsl上仍然还是报这个错，然后下载了benchmark在3rd/benchmark目录下编译，他还是报这个错，应该是要配置环境吧？

之前老版本确实见过benchmark的这个问题，但是后面就改掉了，你把代码目录删掉重新下载，然后按照how_to_build文档说明执行就没问题。我在linux、mac上都可以正常操作。执行build.sh init的时候，如果没有root权限，要加上sudo
