### ISSUE TITLE
[BUG] build relase failed

### ISSUE THREAD

**Issue by shaojintian** [oceanbase/miniob#192]
**Describe the bug**

** Environment**
Environment Details sometimes important
- OS Version: macos
- CPU Arch(x86/arm): m1
- Compiler: clang 14
- Others:

**Fast Reproduce Steps(Required)**
branch main
./build.sh release

**Expected behavior**

**Actual Behavior**
[ 22%] Building CXX object src/observer/CMakeFiles/observer_static.dir/sql/parser/yacc_sql.cpp.o
yacc_sql.cpp:1378:9: error: variable 'yynerrs' set but not used [-Werror,-Wunused-but-set-variable]
    int yynerrs = 0;
        ^
yacc_sql.cpp:1378:9: error: variable 'yynerrs' set but not used [-Werror,-Wunused-but-set-variable]
    int yynerrs = 0;
        ^
1 error generated.
1 error generated.
make[2]: *** [src/observer/CMakeFiles/observer.dir/sql/parser/yacc_sql.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [src/observer/CMakeFiles/observer_static.dir/sql/parser/yacc_sql.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/Users/jintianv/Desktop/miniob/src/observer/sql/operator/insert_physical_operator.cpp:24:30: error: unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]
    : table_(table), values_(move(values))
                             ^
                             std::
/Users/jintianv/Desktop/miniob/src/observer/sql/optimizer/optimize_stage.cpp:265:31: error: unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]
    predicate_oper->add_child(move(table_oper));
                              ^
                              std::
/Users/jintianv/Desktop/miniob/src/observer/sql/optimizer/optimize_stage.cpp:266:29: error: unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]
    project_oper->add_child(move(predicate_oper));
                            ^
                            std::
/Users/jintianv/Desktop/miniob/src/observer/sql/optimizer/optimize_stage.cpp:268:29: error: unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]
    project_oper->add_child(move(table_oper));
                            ^
                            std::
/Users/jintianv/Desktop/miniob/src/observer/sql/operator/insert_physical_operator.cpp:24:30: error: unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]
    : table_(table), values_(move(values))
                             ^
                             std::
/Users/jintianv/Desktop/miniob/src/observer/sql/optimizer/optimize_stage.cpp:265:31: error: unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]
    predicate_oper->add_child(move(table_oper));
                              ^
                              std::
/Users/jintianv/Desktop/miniob/src/observer/sql/optimizer/optimize_stage.cpp:266:29: error: unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]
    project_oper->add_child(move(predicate_oper));
                            ^
                            std::
/Users/jintianv/Desktop/miniob/src/observer/sql/optimizer/optimize_stage.cpp:268:29: error: unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]
    project_oper->add_child(move(table_oper));
                            ^
                            std::
/Users/jintianv/Desktop/miniob/src/observer/sql/optimizer/optimize_stage.cpp:299:88: error: unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]
    predicate_oper = unique_ptr<PredicateLogicalOperator>(new PredicateLogicalOperator(move(conjunction_expr)));
                                                                                       ^
                                                                                       std::
/Users/jintianv/Desktop/miniob/src/observer/sql/optimizer/optimize_stage.cpp:302:22: error: unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]
  logical_operator = move(predicate_oper);
                     ^
                     std::
/Users/jintianv/Desktop/miniob/src/observer/sql/optimizer/physical_plan_generator.cpp:131:37: error: unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]
    index_scan_oper->set_predicates(move(predicates));
                                    ^
                                    std::
1 error generated.
/Users/jintianv/Desktop/miniob/src/observer/sql/optimizer/physical_plan_generator.cpp:136:37: error: unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]
    table_scan_oper->set_predicates(move(predicates));
                                    ^
                                    std::
/Users/jintianv/Desktop/miniob/src/observer/sql/optimizer/physical_plan_generator.cpp:161:39: error: unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]
  unique_ptr<Expression> expression = move(expressions.front());
                                      ^
                                      std::
/Users/jintianv/Desktop/miniob/src/observer/sql/optimizer/physical_plan_generator.cpp:162:69: error: unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]
  oper = unique_ptr<PhysicalOperator>(new PredicatePhysicalOperator(move(expression)));
                                                                    ^
                                                                    std::
/Users/jintianv/Desktop/miniob/src/observer/sql/optimizer/physical_plan_generator.cpp:163:19: error: unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]
  oper->add_child(move(child_phy_oper));
                  ^
                  std::
/Users/jintianv/Desktop/miniob/src/observer/sql/optimizer/physical_plan_generator.cpp:190:33: error: unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]
    project_operator->add_child(move(child_phy_oper));
                                ^
                                std::
/Users/jintianv/Desktop/miniob/src/observer/sql/optimizer/physical_plan_generator.cpp:203:79: error: unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]
  InsertPhysicalOperator *insert_phy_oper = new InsertPhysicalOperator(table, move(values));
                                                                              ^
                                                                              std::
/Users/jintianv/Desktop/miniob/src/observer/sql/optimizer/physical_plan_generator.cpp:227:21: error: unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]
    oper->add_child(move(child_physical_oper));
                    ^
                    std::
make[2]: *** [src/observer/CMakeFiles/observer.dir/sql/operator/insert_physical_operator.cpp.o] Error 1
/Users/jintianv/Desktop/miniob/src/observer/sql/optimizer/optimize_stage.cpp:338:31: error: unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]
    predicate_oper->add_child(move(table_get_oper));
                              ^
                              std::
/Users/jintianv/Desktop/miniob/src/observer/sql/optimizer/optimize_stage.cpp:339:28: error: unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]
    delete_oper->add_child(move(predicate_oper));
                           ^
                           std::
/Users/jintianv/Desktop/miniob/src/observer/sql/optimizer/optimize_stage.cpp:341:28: error: unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]
    delete_oper->add_child(move(table_get_oper));
                           ^
                           std::
/Users/jintianv/Desktop/miniob/src/observer/sql/optimizer/optimize_stage.cpp:344:22: error: unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]
  logical_operator = move(delete_oper);
                     ^
                     std::
/Users/jintianv/Desktop/miniob/src/observer/sql/optimizer/physical_plan_generator.cpp:246:38: error: unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]
    explain_physical_oper->add_child(move(child_physical_oper));
                                     ^
                                     std::
/Users/jintianv/Desktop/miniob/src/observer/sql/optimizer/physical_plan_generator.cpp:249:10: error: unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]
  oper = move(explain_physical_oper);
         ^
         std::
/Users/jintianv/Desktop/miniob/src/observer/sql/optimizer/physical_plan_generator.cpp:272:35: error: unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]
    join_physical_oper->add_child(move(child_physical_oper));
                                  ^
                                  std::
/Users/jintianv/Desktop/miniob/src/observer/sql/optimizer/physical_plan_generator.cpp:275:10: error: unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]
  oper = move(join_physical_oper);
         ^
         std::
/Users/jintianv/Desktop/miniob/src/observer/sql/optimizer/physical_plan_generator.cpp:131:37: error: unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]
    index_scan_oper->set_predicates(move(predicates));
                                    ^
                                    std::
/Users/jintianv/Desktop/miniob/src/observer/sql/optimizer/physical_plan_generator.cpp:136:37: error: unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]
    table_scan_oper->set_predicates(move(predicates));
                                    ^
                                    std::
/Users/jintianv/Desktop/miniob/src/observer/sql/optimizer/optimize_stage.cpp:299:88: error: unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]
    predicate_oper = unique_ptr<PredicateLogicalOperator>(new PredicateLogicalOperator(move(conjunction_expr)));
                                                                                       ^
                                                                                       std::
/Users/jintianv/Desktop/miniob/src/observer/sql/optimizer/optimize_stage.cpp:302:22: error: unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]
  logical_operator = move(predicate_oper);
                     ^
                     std::
/Users/jintianv/Desktop/miniob/src/observer/sql/operator/table_scan_physical_operator.cpp:78:17: error: unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]
  predicates_ = move(exprs);
                ^
                std::
/Users/jintianv/Desktop/miniob/src/observer/sql/optimizer/physical_plan_generator.cpp:161:39: error: unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]
  unique_ptr<Expression> expression = move(expressions.front());
                                      ^
                                      std::
/Users/jintianv/Desktop/miniob/src/observer/sql/optimizer/physical_plan_generator.cpp:162:69: error: unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]
  oper = unique_ptr<PhysicalOperator>(new PredicatePhysicalOperator(move(expression)));
                                                                    ^
                                                                    std::
/Users/jintianv/Desktop/miniob/src/observer/sql/optimizer/physical_plan_generator.cpp:163:19: error: unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]
  oper->add_child(move(child_phy_oper));
                  ^
                  std::
/Users/jintianv/Desktop/miniob/src/observer/sql/optimizer/physical_plan_generator.cpp:190:33: error: unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]
    project_operator->add_child(move(child_phy_oper));
                                ^
                                std::
/Users/jintianv/Desktop/miniob/src/observer/sql/optimizer/physical_plan_generator.cpp:203:79: error: unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]
  InsertPhysicalOperator *insert_phy_oper = new InsertPhysicalOperator(table, move(values));
                                                                              ^
                                                                              std::
/Users/jintianv/Desktop/miniob/src/observer/sql/optimizer/physical_plan_generator.cpp:227:21: error: unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]
    oper->add_child(move(child_physical_oper));
                    ^
                    std::
/Users/jintianv/Desktop/miniob/src/observer/sql/optimizer/physical_plan_generator.cpp:246:38: error: unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]
    explain_physical_oper->add_child(move(child_physical_oper));
                                     ^
                                     std::
/Users/jintianv/Desktop/miniob/src/observer/sql/optimizer/physical_plan_generator.cpp:249:10: error: unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]
  oper = move(explain_physical_oper);
         ^
         std::
1 error generated.
/Users/jintianv/Desktop/miniob/src/observer/sql/optimizer/physical_plan_generator.cpp:272:35: error: unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]
    join_physical_oper->add_child(move(child_physical_oper));
                                  ^
                                  std::
/Users/jintianv/Desktop/miniob/src/observer/sql/optimizer/physical_plan_generator.cpp:275:10: error: unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]
  oper = move(join_physical_oper);
         ^
         std::
/Users/jintianv/Desktop/miniob/src/observer/sql/operator/table_scan_physical_operator.cpp:78:17: error: unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]
  predicates_ = move(exprs);
                ^
                std::
/Users/jintianv/Desktop/miniob/src/observer/sql/optimizer/optimize_stage.cpp:338:31: error: unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]
    predicate_oper->add_child(move(table_get_oper));
                              ^
                              std::
/Users/jintianv/Desktop/miniob/src/observer/sql/optimizer/optimize_stage.cpp:339:28: error: unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]
    delete_oper->add_child(move(predicate_oper));
                           ^
                           std::
/Users/jintianv/Desktop/miniob/src/observer/sql/optimizer/optimize_stage.cpp:341:28: error: unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]
    delete_oper->add_child(move(table_get_oper));
                           ^
                           std::
/Users/jintianv/Desktop/miniob/src/observer/sql/optimizer/optimize_stage.cpp:344:22: error: unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]
  logical_operator = move(delete_oper);
                     ^
                     std::
make[2]: *** [src/observer/CMakeFiles/observer_static.dir/sql/operator/insert_physical_operator.cpp.o] Error 1
12 errors generated.
make[2]: *** [src/observer/CMakeFiles/observer_static.dir/sql/optimizer/physical_plan_generator.cpp.o] Error 1
19 error error generateds.
 generated.
12 errors generated.
make[2]: *** [src/observer/CMakeFiles/observer_static.dir/sql/operator/table_scan_physical_operator.cpp.o] Error 1
make[2]: *** [src/observer/CMakeFiles/observer_static.dir/sql/optimizer/optimize_stage.cpp.o] Error 1
make[1]: *** [src/observer/CMakeFiles/observer_static.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
1 error generated.
make[2]: *** [src/observer/CMakeFiles/observer.dir/sql/optimizer/physical_plan_generator.cpp.o] Error 1
make[2]: *** [src/observer/CMakeFiles/observer.dir/sql/operator/table_scan_physical_operator.cpp.o] Error 1
9 errors generated.
make[2]: *** [src/observer/CMakeFiles/observer.dir/sql/optimizer/optimize_stage.cpp.o] Error 1
make[1]: *** [src/observer/CMakeFiles/observer.dir/all] Error 2
make: *** [all] Error 2

**Additional context**

**Comment by hnwyllmm** [comment]
你的clang版本比较高，我现在还没有重新，正在升级clang，稍后回复
