### ISSUE TITLE
需要发布最新版的docker镜像

### ISSUE THREAD

**Issue by hnwyllmm** [oceanbase/miniob#205]
**Enhancement**
当前的miniob编译初始化方式与现有的docker镜像差别很大，并且代码也已经更新了很多。

**Comment by OriPoin** [comment]
在官方发布的Docker镜像和使用仓库里面的dockerfile编译的镜像都不能编译过。报错如下

```
/root/miniob/src/observer/storage/trx/mvcc_trx.cpp: In member function ‘virtual void MvccTrxKit::destroy_trx(Trx*)’:
/root/miniob/src/observer/storage/trx/mvcc_trx.cpp:88:3: error: ‘erase’ was not declared in this scope
   erase(trxes_, trx);
   ^~~~~
/root/miniob/src/observer/storage/trx/mvcc_trx.cpp:88:3: note: suggested alternative: ‘Frame’
   erase(trxes_, trx);
   ^~~~~
   Frame
```

在ubuntu:latest镜像中，使用git submodules构建依赖可以编译过

**Comment by hnwyllmm** [comment]
> 在官方发布的Docker镜像和使用仓库里面的dockerfile编译的镜像都不能编译过。报错如下
> 
> ```
> /root/miniob/src/observer/storage/trx/mvcc_trx.cpp: In member function ‘virtual void MvccTrxKit::destroy_trx(Trx*)’:
> /root/miniob/src/observer/storage/trx/mvcc_trx.cpp:88:3: error: ‘erase’ was not declared in this scope
>    erase(trxes_, trx);
>    ^~~~~
> /root/miniob/src/observer/storage/trx/mvcc_trx.cpp:88:3: note: suggested alternative: ‘Frame’
>    erase(trxes_, trx);
>    ^~~~~
>    Frame
> ```
> 
> 在ubuntu:latest镜像中，使用git submodules构建依赖可以编译过

Thanks very much. This issue fixed by #221

**Comment by OriPoin** [comment]
使用Ubuntu构建了一个docker镜像，commit在https://github.com/oceanbase/miniob/commit/cb186f1d7f8625d38126683e9460d2d12492b503
另外不知道想要合并进miniob的话是否需要使用anolisos？

**Comment by hnwyllmm** [comment]
> 使用Ubuntu构建了一个docker镜像，commit在[cb186f1](https://github.com/oceanbase/miniob/commit/cb186f1d7f8625d38126683e9460d2d12492b503) 另外不知道想要合并进miniob的话是否需要使用anolisos？

非常感谢。不是一定要anolisos，选一个开发者最喜欢用的操作系统更好。
能不能提交一个PR？
另外，代码中没有安装Bison, 是包含在某个工具包中了吗？

**Comment by hnwyllmm** [comment]
ref #111

**Comment by hnwyllmm** [comment]
镜像已发布。
