### ISSUE TITLE
记录管理部分的page_header_初始化的疑问

### ISSUE THREAD

**Issue by JugendTraum** [oceanbase/miniob#226]
```c++
  int page_size                     = BP_PAGE_DATA_SIZE;
  int record_phy_size               = align8(record_size);
  page_header_->record_num          = 0;
  page_header_->record_capacity     = page_record_capacity(page_size, record_phy_size);
  page_header_->record_real_size    = record_size;
  page_header_->record_size         = record_phy_size;
  page_header_->first_record_offset = page_header_size(page_header_->record_capacity);
```
此处的record_capacity的计算并没有考虑8字节对齐，计算的是不对齐时页面下容纳的最大记录量。但first_record_offset将PageHeader和位图大小8字节对齐，那么最后一个记录不是会超出页面大小吗？

![image](https://github.com/oceanbase/miniob/assets/111098930/590fc6ed-82b5-4076-93dd-5df85038b495)
上图是单元测试record_manager_test.cpp调试过程的变量值，152 + 1005 * 8 = 8192 > 8188 = page_size

不知道我上述思考是否是对的，请解答一下谢谢

**Comment by hnwyllmm** [comment]
你说的是对的,非常感谢。
你想提交一个PR修复这个问题吗？可以把这块逻辑改的简单清晰一些

**Comment by JugendTraum** [comment]
可以的，但我刚开始了解这部分，不清楚要怎么改，具体要哪里对齐？

**Comment by hnwyllmm** [comment]
保证每个记录的第一个字节是8字节对齐的就行。或者不对齐，在x86平台上运行也没有问题的。
你选择一个方式，给出注释就行。
另外可以加一个单测，避免再次出现你说的问题，即保证不会溢出。
