### ISSUE TITLE
[BUG] failed to test basic case (2022)

### ISSUE THREAD

**Issue by hnwyllmm** [oceanbase/miniob#267]
**Describe the bug**

Failed to pass the basic test case(2022)

**Comment by leauny** [comment]
貌似是因为2022年测例中table名，列名是对大小写不敏感的，而当前仓库中table名，列名（一切ID词法解析相关的貌似都是这样）是对大小写敏感的。
![image](https://github.com/oceanbase/miniob/assets/42369176/45cca236-745f-454c-9b2a-fb71a6e20718)

**Comment by hnwyllmm** [comment]
测试程序不区分大小写

**Comment by lxr599** [comment]
是不是测评程序的问题

**Comment by hnwyllmm** [comment]
由于当前代码中事务模式与2022年不同，所以无法通过2022年的basic 测试 case
