### ISSUE TITLE
Following Errors about aggregate functions should be reported at the syntax analysis stage

### ISSUE THREAD

**Issue by ringfa11** [oceanbase/miniob#273]
**Question**
In testcase result file `test/case/result/primary-aggregation-func.result`,
I found that some incorrect usages of aggregate functions are reported as `Failure`

![image](https://github.com/oceanbase/miniob/assets/55312093/fe76fca5-c957-40c0-8d98-f6afe575cbd7)

However, I believe they should be reported as syntax errors. I tried MySQL version 8.0.34 on Windows, and it also gave syntax errors

![1695650298980](https://github.com/oceanbase/miniob/assets/55312093/49be05d0-2085-4200-943f-06ed92c07277)

**Comment by hnwyllmm** [comment]
Good question!
I think you're right. The error message response by observer is not good enough.
Currently, miniob use plain string as the response and request message, so it is difficult to describe information clearly.
As a better option, miniob support mysql protocol now and we can fix such issues by mysql protocol. In the future, we can use mysql protocol as the basic protocol to do test.

**Comment by ringfa11** [comment]
How can I switch to mysql protocal in miniob?
I have tried  ./build/bin/observer -f ./etc/observer.ini -P mysql, but it seems not right.

**Comment by hnwyllmm** [comment]
What's wrong?

**Comment by hnwyllmm** [comment]
Which mysql client did you use?
mysql 8.0 is not tested yet.

**Comment by ringfa11** [comment]
> Which mysql client did you use? mysql 8.0 is not tested yet.


Thanks for your reply.
I got stuck because I just don't know how to connect observer with mysql client......
So I try blindly.
By the way, I have  tried like this. 
At left panel,I start server. 
At right, I try to connect.
Connection seems to build ok, but I can't get a prompt shell.

![image](https://github.com/oceanbase/miniob/assets/55312093/7a4ced41-4da0-455e-8949-15849b132a66)
 My mysql client version is  `Ver 8.0.34`.

**Comment by hnwyllmm** [comment]
Sorry for that mysql-client 8.x is not tested.
I created an issue #274
