### ISSUE TITLE
GitHub提测建议

### ISSUE THREAD

**Issue by leauny** [oceanbase/miniob#283]
希望官方可以给一个公钥，这样就无需手动添加协作者，直接将公钥加入仓库即可提测。

**Comment by hnwyllmm** [comment]
多谢，好想法，后面去测试一下

**Comment by hnwyllmm** [comment]
@leauny 看了下无法将一个public key放到多个账号中，还有其它的建议吗？

**Comment by leauny** [comment]
> @leauny 看了下无法将一个public key放到多个账号中，还有其它的建议吗？ 另一种可行的方法是后台测试人员生成N多个key，然后给每个团队分发

- 可以让团队上传私人令牌（权限控制更充分，相对来说最方便）具体可以参考[gitee镜像仓库教程](https://help.gitee.com/repository/settings/sync-between-gitee-github#%E5%A6%82%E4%BD%95%E7%94%B3%E8%AF%B7-github-%E7%A7%81%E4%BA%BA%E4%BB%A4%E7%89%8C)
- 用gpg公钥创建多个子公私钥（安全，可能方便一些）
- 如果不嫌内容长也可以让队伍提交私钥。
