### ISSUE TITLE
windows用docker怎么开发miniob目录（请尽量详细一点）

### ISSUE THREAD

**Issue by qpoitiuoru** [oceanbase/miniob#288]
**Question**

**Comment by hnwyllmm** [comment]
可以参考这两个
https://oceanbase.github.io/miniob/dev-env/how_to_dev_miniob_by_docker_on_windows.html
https://oceanbase.github.io/miniob/dev-env/how_to_dev_in_docker_container_by_vscode.html

Windows上使用WSL2也可以的。

**Comment by qpoitiuoru** [comment]
请问dockerfile怎么配置

**Comment by qpoitiuoru** [comment]
好的，谢谢
