### ISSUE TITLE
请问为什么在编译miniob时用build.sh后变成这样

### ISSUE THREAD

**Issue by qpoitiuoru** [oceanbase/miniob#293]
![微信图片_20231014191101](https://github.com/oceanbase/miniob/assets/147593225/28b0169a-1ae0-4f6c-b8b5-abb2b38a45a8)

**Comment by hnwyllmm** [comment]
图片没有发出来

**Comment by hnwyllmm** [comment]
刚看到图片。
![image](https://github.com/oceanbase/miniob/assets/5187215/3571e899-d8a4-42bf-828a-4fd000bd62c4)

看起来是执行脚本的目录不对，需要在源码目录下运行脚本。
