### ISSUE TITLE
[BUG] python使用socket文件测试时会出现"粘包"导致输出结果乱码

### ISSUE THREAD

**Issue by leauny** [oceanbase/miniob#301]
问题：python脚本接收到的信息可能存在 `SUCCESS\00SUCCESS`这样的重复现象

仅在使用socket文件时出现，且频繁

![image](https://github.com/oceanbase/miniob/assets/42369176/fa09da98-4d6b-469f-af94-5fcbf269ce65)

https://github.com/oceanbase/miniob/blob/abf5ba72906175de73e178728997f69b55808ba1/src/observer/net/plain_communicator.cpp#L52-L54

不太清楚这里是否有问题，修改为返回0时在调用处不`delete communicator`后似乎可以解决问题。
socket文件非阻塞模式下recv函数返回0是否意味着连接已经断开？
是否是EOF的时候误认为连接断开，然后出现了数据流混乱的问题。

**Comment by hnwyllmm** [comment]
对于read_len==0的问题，可以在手册中得到确认：
```bash
RETURN VALUES
     These calls return the number of bytes received, or -1 if an error occurred.

     For TCP sockets, the return value 0 means the peer has closed its half side of the connection.
```

**Comment by hnwyllmm** [comment]
如果到EOF没有数据，recv应该返回-1，并且errno 是EAGAIN

**Comment by hnwyllmm** [comment]
如果重现的概率比较高，可以在observer和python脚本侧都加一下日志调一下看看

**Comment by hnwyllmm** [comment]
这个问题已经确认，请看 https://github.com/oceanbase/miniob/issues/322

**Comment by hnwyllmm** [comment]
closed by #332
