### ISSUE TITLE
lanunch.json中cppdbg配置为什么要设置externalConsole true

### ISSUE THREAD

**Issue by zhaoyiping0622** [oceanbase/miniob#302]
**Question**

我在wsl2里试了一下，externalConsole true的时候貌似没法正常启动debugger，改为false之后才能启动，所以想问一下之前这里设置为true是有什么特殊用意吗？

**Comment by zhaoyiping0622** [comment]
![image](https://github.com/oceanbase/miniob/assets/39238310/57c310ff-6b78-41b9-b557-8f68808991c1)
![image](https://github.com/oceanbase/miniob/assets/39238310/96d56a5f-72c2-4fb3-a94a-7c9c2214b414)

**Comment by hnwyllmm** [comment]
我的机器是MAC，我在实际测试的时候，如果这个参数不设为true，那么就找不到能够输入数据的终端，但是使用LLDB测试没有问题。
设置为True的话，vscode会启动一个新的terminal，我可以在那里当做客户端输入测试数据。

**Comment by zhaoyiping0622** [comment]
好像所有的远程开发都会碰到这个问题，我Mac试着连了一下远程的docker也不能启动，vscode-remote那边好像也有人提了这个问题：https://github.com/microsoft/vscode-remote-release/issues/3413。要不把externalConsole true设置为osx专有的参数？其他os都用false

**Comment by hnwyllmm** [comment]
创建了一个issue关联此问题，此问题暂时关闭。
后续有其他问题欢迎随时讨论。
