### ISSUE TITLE
[BUG] faild to complie on macOS Sonoma, Apple Silicon

### ISSUE THREAD

**Issue by laofan13** [oceanbase/miniob#306]
**Describe the bug**

[ 24%] Built target common
[ 25%] Built target obclient
[ 78%] Built target observer_static
[ 78%] Linking CXX executable ../../bin/observer
ld: multiple errors: archive member '/' not a mach-o file in '/usr/local/lib/libevent_pthreads.a'; archive member '/' not a mach-o file in '/usr/local/lib/libevent_core.a'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/observer] Error 1
make[1]: *** [src/observer/CMakeFiles/observer.dir/all] Error 2
make: *** [all] Error 2

** Environment**
Apple clang version 15.0.0 (clang-1500.1.0.1.1)
Target: arm64-apple-darwin23.1.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Fast Reproduce Steps(Required)**

**Expected behavior**

**Actual Behavior**
What is the result? picture is allowed

**Additional context**

**Comment by hnwyllmm** [comment]
Did you copy the libevent libraries from other system?
Please remove those libraries and do the command below and try again.
```bash
bash build.sh init
```

or 
```bash
sudo bash build.sh init
```

**Comment by laofan13** [comment]
> Did you copy the libevent libraries from other system? Please remove those libraries and do the command below and try again.
> 
> ```shell
> bash build.sh init
> ```
> 
> or
> 
> ```shell
> sudo bash build.sh init
> ```

No libevent libraries on my macos, I followed the steps above.

**Comment by hnwyllmm** [comment]
What's wrong? Do you have any information?

**Comment by laofan13** [comment]
> What's wrong? Do you have any information?

now it can work, thanks.

**Comment by rybalkoss** [comment]
@laofan13 could you share the solution that worked for you?

**Comment by hnwyllmm** [comment]
> @laofan13 could you share the solution that worked for you?

Do you have any virtual environment tools on your system?

**Comment by laofan13** [comment]
> > @laofan13 could you share the solution that worked for you?
> 
> Do you have any virtual environment tools on your system?

Hi @hnwyllmm ，it can work without change.
