### ISSUE TITLE
[BUG] buffer pool page原子写入问题

### ISSUE THREAD

**Issue by hnwyllmm** [oceanbase/miniob#334]
**Describe the bug**

假设一个buffer pool 页面是8K，那么一个页面在写入磁盘只写入了一部分系统就挂了，恢复时就会出现问题。
需要保证8K要么一次性全部写入，要么不写入，或者写入一部分时有能力检测出异常并恢复。

可以参考 MySQL或PostgreSQL的做法。

**Comment by Wenbin1002** [comment]
参考InnoDB的double write吗？那恢复的逻辑怎么写呢，miniob的page好像没有校验码吧。

**Comment by hnwyllmm** [comment]
校验码没有问题，可以加上来。
MiniOB完全不需要考虑新旧版本兼容的问题。

**Comment by Wenbin1002** [comment]
我遇到了一个问题，miniob的每一个DiskBufferPool是关联到某一个具体文件的，那么当我想要向磁盘上对应的double write buffer中写入的时候还要再开一个DiskBufferPool。所以要同时对两个DiskBufferPool进行操作，我目前的想法是在BufferPoolManager中进行操作时候再重复写一遍对double write buffer的操作，但是感觉逻辑上比较麻烦，有什么更好的解决方案吗？

**Comment by hnwyllmm** [comment]
确实。用做镜像的buffer，不应该与普通的buffer 放在一起，特别是不应该放在同一个frame manager中竞争Frame。他们的页面内存淘汰策略是不同的。
我建议参考MySQL的设计，实现单独的double write buffer，但是可以简化。
比如设计一个公共的“表空间”，一个disk buffer pool，它使用自己单独的frame manager，有自己特有的内存淘汰策略。这个空间第一个页面用于记录元数据，包含了每个页面是否使用、与镜像页面的关系等。由于这个空间中的页面在镜像页面确认没有问题后，就可以重用，所以总体上这个空间不需要太大，一个元数据页面就够了。

可以参考：
mysql:
https://cloud.tencent.com/developer/article/1630526
https://zhuanlan.zhihu.com/p/272720373

postgresql:
https://zhuanlan.zhihu.com/p/426218020
https://blog.csdn.net/weixin_44375561/article/details/123633181

**Comment by hnwyllmm** [comment]
我看到你已经提交了CRC校验的代码，想要提交到主仓来吗？可以先把这部分代码提交上来。

**Comment by Wenbin1002** [comment]
好的我再看看。crc的代码是我提一个新issue还是直接提pr？

**Comment by hnwyllmm** [comment]
> 好的我再看看。crc的代码是我提一个新issue还是直接提pr？

建一个新的issue，跟这个issue关联起来，然后提PR吧

**Comment by hnwyllmm** [comment]
方便的话加个微信 hnwyllmm_126
