### ISSUE TITLE
docker拉取镜像太慢

### ISSUE THREAD

**Issue by wanglufee** [oceanbase/miniob#368]
添加了阿里云镜像之后拉取依然很慢，有什么办法解决吗？

**Comment by hnwyllmm** [comment]
oceanbase/miniob 镜像就是一个普通的镜像，当前没有为它在其他仓库设置缓存。
如果你确实拉取很慢，可以联系我给你发送一个镜像 （微信 hnwyllmm_126，邮箱 hnwyllmm@126.com）

**Comment by wanglufee** [comment]
你好，我加你微信了，多谢！
