### ISSUE TITLE
添加 '#include<cstdint>' 到 common/types.h第一行

### ISSUE THREAD

**Issue by 707state** [oceanbase/miniob#378]
oponsuse tw上用g++编译，需要在src/observer/common/types.h中添加#include<cstdint>，main分支。可能是gcc版本问题？

**Comment by hnwyllmm** [comment]
这个问题确实与gcc版本有关系。gcc 12可以编译通过，但是13会失败。
可以在 common/types.h 中增加一个 #include <stdint.h>
可以帮忙提个PR吗？

**Comment by 707state** [comment]
> 这个问题确实与gcc版本有关系。gcc 12可以编译通过，但是13会失败。 可以在 common/types.h 中增加一个 #include <stdint.h> 可以帮忙提个PR吗？

好的，已经提了

**Comment by hnwyllmm** [comment]
closed by #379
