### ISSUE TITLE
编译后无法启动miniob

### ISSUE THREAD

**Issue by Ox4A** [oceanbase/miniob#390]
**Question**
2023-05-05
环境：Win 11上通过docker部署（已拉取镜像）
克隆oceanbase-competition-2023分支的代码，并映射到docker后，
bash build.sh init、bash build.sh完成编译（build.sh中删除了-j $CPU_CORES），
运行：./build_debug/bin/observer f ./etc/observer.ini -P cli无法启动，报错：
Configuration hasn't set ThreadPools
Failed to init thread pool

SedaConfig: unable to initialize seda stages
Failed to init seda configuration!
Shutdown due to failed to init!
但是克隆main分支经过同样步骤可以运行，怎么解决？是因为最新的镜像和oceanbase-competion-2023这个分支不适配了吗？

**Comment by hnwyllmm** [comment]
你的运行命令，应该是-f 少了减号

**Comment by hnwyllmm** [comment]
长时间没有回复，关闭issue
