### ISSUE TITLE
[BUG]构建的Docker开发容器无法使用root密码登录

### ISSUE THREAD

**Issue by CHELO-NG** [oceanbase/miniob#394]
**Bug描述**
构建的Docker开发容器无法使用root密码登录

![Pasted image 20240510095916](https://github.com/oceanbase/miniob/assets/59860906/587bfe39-d8e5-40a5-8184-c46e73a4150e)

**Bug分析**

可能是sshd由于版本升级，增加了如下的默认配置，导致不允许root通过密码登录。

![Pasted image 20240510100455](https://github.com/oceanbase/miniob/assets/59860906/9da18703-5712-47cf-a13b-16f1478db5c8)

可以修改该配置允许root用户通过密码登录

```config
PermitRootLogin yes
```

**Bug解决方案**

方案一：

在相关文档中增加相关问题的解决方案。

方案二：

修改docker/bin/starter-sshd.sh文件

```bash
if [ -f /etc/ssh/sshd_config ]; then
  echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
  service ssh restart
fi
```

**Comment by hnwyllmm** [comment]
感谢反馈，可以帮忙提个PR吗？
