### ISSUE TITLE
A question about the feature about updateing,deleting and changing index

### ISSUE THREAD

**Issue by lychnin** [oceanbase/miniob#417]
I have read the code in ./src/observer/storage.Now I want to explore which mode uses the feature about bplus index.But I just found the creat_index_executor.cpp/h and create_index_stmt.cpp/h using the API.

So my question is if the miniob have not finished the feature about updateing,deleting and changing index.

**Comment by hnwyllmm** [comment]
MiniOB supports inserting, deleting b+tree index.

**Comment by lychnin** [comment]
Sorry,what I mean is if miniob has not finished the feature "change_index" just like create_index_executor.cpp which could call b+tree's inserting,deleting function.
![屏幕截图 2024-05-22 201730](https://github.com/oceanbase/miniob/assets/78843493/2e8affdc-6085-46f4-bf7e-72b646ae660a)

**Comment by hnwyllmm** [comment]
create_index_executor is just for creating index.
What do you mean about 'changing' index? The type? Type meta?

**Comment by lychnin** [comment]
Sorry,I make a mistake.I've just learned changing index is droping the index and creating a new index which has the same name as the origin index.

**Comment by hnwyllmm** [comment]
You're right. You can't even drop an index right now in MiniOB.
