### ISSUE TITLE
About the using of class SessionStage

### ISSUE THREAD

**Issue by lychnin** [oceanbase/miniob#418]
I found the class SessionStage was only used in the class SqlTaskHandler and only its function handle_request2 was used.

So my question is if moniob have not finished the logic about using of class SessionStage.

**Comment by hnwyllmm** [comment]
Yes, there's no more features needed.
But we should do something to optimize the code, such as remove the `handle_request` function.

**Comment by lychnin** [comment]
Thanks for your replying.
