### ISSUE TITLE
HelloGitHub Badge

### ISSUE THREAD

**Issue by 521xueweihan** [oceanbase/miniob#424]
🎉 Congratulations! Your [project](https://hellogithub.com/repository/62efc8a5bbb64a9fbb1ebb7703446f36) has been featured and recommended by the HelloGitHub community. We invite you to join the HelloGitHub Badge Program. Joining will grant you the following privileges:

- **Community Recognition**: The badge indicates that your project has successfully passed the HelloGitHub community's stringent selection and recommendation process.
- **Increased Exposure**: Displaying the badge will draw more traffic to your project, attracting additional users and contributors.
- **Enhanced Interaction**: Users can quickly understand your project through the badge and engage with it (like, comment, bookmark).
- **Feedback Collection**: Gather genuine feedback from a broad user base, aiding in the continuous improvement of your project.
- **Special Identification**: Once verified, your comments will feature a distinctive mark and be prioritized for pinning.

📌 [Click here](https://hellogithub.com/repository/62efc8a5bbb64a9fbb1ebb7703446f36/embed) to wear the badge and join the HelloGitHub Badge Program, allowing your open-source project to shine even brighter.

---

**HelloGitHub** is a community focused on discovering, sharing, and promoting open-source projects. Since its inception in 2016, it has grown from a monthly newsletter into a dynamic community with over **10,000** users. Our footprint extends across multiple content platforms, earning the trust and support of **500,000** fans worldwide.

<img width="1245" alt="截屏2024-06-12 09 29 42" src="https://github.com/No-Chicken/OV-Watch/assets/8255800/7ac6b71e-f052-4f44-88b1-5c772e917348">

**Comment by hnwyllmm** [comment]
Thanks a lot. HelloGitHub is a wonderful project. But the badge is too big and doesn’t look good next to other icons. Can you provide more styles?

**Comment by 521xueweihan** [comment]
@hnwyllmm Thank you for your response. The badge size can be adjusted by modifying `style="width: 250px; height: 54px;" width="250" height="54"`. However, if you are looking for a mini badge, I will need more time to develop it. Is it something like this?

<img width="331" alt="image" src="https://github.com/oceanbase/miniob/assets/8255800/784a6d98-8a1a-44bd-8aa0-91fe8bb2bd1e">

**Comment by hnwyllmm** [comment]
Yes, I knew it and I have tried it with half size in my personal repo:
https://github.com/hnwyllmm/miniob
It seems "width=250 height=54" is a better size but it's too big.

**Comment by 521xueweihan** [comment]
@hnwyllmm Okay, I will notify you once I have developed the small style badge.

**Comment by 521xueweihan** [comment]
@hnwyllmm Hello, the new minimalist badge has been launched. You are welcome to wear it and claim your project.

<img width="693" alt="截屏2024-07-04 16 00 22" src="https://github.com/oceanbase/miniob/assets/8255800/d7e366e2-9640-4a8a-8c34-0bc878d7b883">

📌 [Click here](https://hellogithub.com/repository/62efc8a5bbb64a9fbb1ebb7703446f36/embed) to wear the badge and join the HelloGitHub Badge Program, allowing your open-source project to shine even brighter.

**Comment by hnwyllmm** [comment]
Wonderful

**Comment by 521xueweihan** [comment]
@hnwyllmm Thank you again for your claim!

Could you please do me a favor and click on 'Submit' on the badge wearing page above? Once I approve it, your project will be pinned at the top of the entire site for one day.

**Comment by hnwyllmm** [comment]
DONE
