### ISSUE TITLE
Error when compiling miniob on mac

### ISSUE THREAD

**Issue by DBMSTesting** [oceanbase/miniob#427]
**Question**
Hello, I encountered a problem when compiling miniob on Mac. My cmake version is 3.30.0. When executing bash build.sh init, I encountered the following error: 

CMake Error: The source directory "/miniob-main/deps/3rd/googletest" does not appear to contain CMakeLists.txt.

I consulted the information, but it was not solved. There is no CMakeLists.txt file in the error. I tried to change the source folder but it did not solve it. Do you have a good solution?

**Comment by hnwyllmm** [comment]
In build.sh init, git submodule will be used to download third-party dependencies such as googletest. You can check whether the deps/3rd/googletest code is downloaded successfully.

**Comment by hnwyllmm** [comment]
closed as no response in a long time.
