### ISSUE TITLE
增加识别 CMAKE_BUILD_TYPE 选项，删除 DEBUG=ON Cmake选项

### ISSUE THREAD

**Issue by hnwyllmm** [oceanbase/miniob#432]
**Enhancement**
CMAKE_BUILD_TYPE 是更通用的， Cmake 提供的选项。而 -DDEBUG=ON 需要自己识别并增加编译选项。
CMAKE_BUILD_TYPE 可以适用于更多的开发环境。比如在CLion中，会默认配置 CMAKE_BUILD_TYPE 为 Debug，但是由于 CMakeLists.txt 中并未识别 CMAKE_BUILD_TYPE 导致编译代码不是DEBUG版本。

参考 [CMAKE_BUILD_TYPE 手册](https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html#variable:CMAKE_BUILD_TYPE)

**Comment by LvNing-bwt** [comment]
请问这个问题现在实现了吗，我可以尝试一下去解决这个问题吗

**Comment by hnwyllmm** [comment]
十分感谢，assign给你了。

**Comment by LvNing-bwt** [comment]
我天，不好意思，第一次尝试解决一个问题，请问一下我刚刚好像点错了，是不小心把任务撤销了吗

**Comment by hnwyllmm** [comment]
> 我天，不好意思，第一次尝试解决一个问题，请问一下我刚刚好像点错了，是不小心把任务撤销了吗

转给你了。
有兴趣可以加我微信 hnwyllmm_126 我们有个开发者群，有问题可以更快的沟通

**Comment by LvNing-bwt** [comment]
好的！太感谢了！！
