### ISSUE TITLE
测试样例结果中的行为和mysql的行为不一致

### ISSUE THREAD

**Issue by LbuprofenL** [oceanbase/miniob#444]
**Question**
在测试primary_date时，发现测试样例结果中的行为和mysql的行为不一致。
下面是mysql的结果，对于非法日期的比较不会报错
![image](https://github.com/user-attachments/assets/ae5ffae0-372b-4bcd-96a9-cbd326683b13)
而在primary_date.result中的要求输出是FAILURE
![image](https://github.com/user-attachments/assets/110b0a6a-9437-4e54-a615-d30a51e6bf7c)

**Comment by hnwyllmm** [comment]
训练营中当前使用的是ubuntu22.04中默认安装的MySQL，版本是8，与5.7或者之前版本表现不一样。
> 问题已在答疑群回复。
