### ISSUE TITLE
Ambiguous symbol 'filesystem'

### ISSUE THREAD

**Issue by Kosthi** [oceanbase/miniob#446]
**Enhancement**
在 CLion 中提示 Ambiguous symbol 'filesystem'，但是不影响正常编译。
原因是命名空间 filesystem 与 std::filesystem 产生名称冲突。
建议：可以移除 using namespace std 代码以防止潜在的命名冲突。

```
➜  ~ clang --version
Homebrew clang version 18.1.8
Target: arm64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /opt/homebrew/opt/llvm/bin
```

<img width="1095" alt="Screen Shot 2024-09-15 at 00 53 38" src="https://github.com/user-attachments/assets/ddf4b616-68c0-4920-bf8f-561e700cb5fb">

**Comment by hnwyllmm** [comment]
这里并没有新增filesystem命名空间或者类名，或类似内容，并没有什么内容与std::filesystem重复。看起来是clion识别的不是很准确？

**Comment by Kosthi** [comment]
> 这里并没有新增filesystem命名空间或者类名，或类似内容，并没有什么内容与std::filesystem重复。看起来是clion识别的不是很准确？

有可能，毕竟编译也没问题。
