### ISSUE TITLE
[BUG]IntegerType::compare function

### ISSUE THREAD

**Issue by Kosthi** [oceanbase/miniob#450]
**Describe the bug**
当右值为浮点数，int 类型数据地址在调用 ```common::compare_float``` 时被直接解析成 float 类型，这是未定义的行为，且第二个参数应该传入 ```right.value_.float_value_```。

```cpp
int IntegerType::compare(const Value &left, const Value &right) const
{
  ASSERT(left.attr_type() == AttrType::INTS, "left type is not integer");
  ASSERT(right.attr_type() == AttrType::INTS || right.attr_type() == AttrType::FLOATS, "right type is not numeric");
  if (right.attr_type() == AttrType::INTS) {
    return common::compare_int((void *)&left.value_.int_value_, (void *)&right.value_.int_value_);
  } else if (right.attr_type() == AttrType::FLOATS) {
    return common::compare_float((void *)&left.value_.int_value_, (void *)&right.value_.int_value_);
  }
  return INT32_MAX;
}
```

** Environment**
Environment Details sometimes important
- OS Version:
- CPU Arch(x86/arm):
- Compiler: 
- Others:

**Fast Reproduce Steps(Required)**

**Expected behavior**

**Actual Behavior**
What is the result? picture is allowed

**Additional context**

**Comment by hnwyllmm** [comment]
感谢指出，这种做法确实不合理。
可以帮忙提PR吗？

**Comment by Kosthi** [comment]
> 感谢指出，这种做法确实不合理。 可以帮忙提PR吗？

已提交pr
