### ISSUE TITLE
Implement miniob on systems based on MUSL LIBC

### ISSUE THREAD

**Issue by bLueriVerLHR** [oceanbase/miniob#453]
**Enhancement**

I was trying to implement miniob on alpine linux for further development. However, the `MUSL LIBC` do not support all the features that common `GNU LIBC` supports like address sanitizer. I did not find a solution and turn the option off sadly. But I did successfully compile the project on alpine linux after some fixes.

1. Function [get_process_name](https://github.com/oceanbase/miniob/blob/50d3a28bb3e0e235960a580e3148ea00f53c15bf/deps/common/os/process.cpp#L38-L57) use `basename()` in its implementation while not including header file `libgen.h`. I try to fix this problem using following implementation. It needs `filesystem` instead, but more cpp way I thought.

``` cpp
string get_process_name(const char *prog_name)
{
  return std::filesystem::path(prog_name).filename().c_str();
}
```

2. Systems not using `GNU LIBC` may not have macros like `PTHREAD_ERRORCHECK_MUTEX_INITIALIZER_NP` and `PTHREAD_ERRORCHECK_MUTEX_INITIALIZER`. For example, `MUSL LIBC` has pthread api while not implementing the macros mentioned before. Here is the [explanation](https://musl.openwall.narkive.com/pIg9flJT/no-definition-of-pthread-recursive-mutex-initializer-np-in). I do not know much about mutexattr right now, so I try to fix problem on [source code](https://github.com/oceanbase/miniob/blob/50d3a28bb3e0e235960a580e3148ea00f53c15bf/deps/common/time/datetime.cpp#L351-L355) using code list below. Bad as not detecting if using `MUSL LIBC`, but fixed the problem.

``` cpp
#if defined(LINUX)
  #if not defined(__USE_GNU__)
    static pthread_mutexattr_t mtxattr;
    static pthread_mutexattr_t *pmtxattr = nullptr;
    static pthread_mutex_t mutex = PTHREAD_MUTEX_INITIALIZER;
    if (pmtxattr == nullptr) {
      pmtxattr = &mtxattr;
      pthread_mutexattr_init(pmtxattr);
      pthread_mutexattr_settype(pmtxattr, PTHREAD_MUTEX_ERRORCHECK);
      pthread_mutex_init(&mutex, pmtxattr);
    }
  #else
    static pthread_mutex_t mutex = PTHREAD_ERRORCHECK_MUTEX_INITIALIZER_NP;
  #endif
#elif defined(__MACH__)
  static pthread_mutex_t mutex = PTHREAD_ERRORCHECK_MUTEX_INITIALIZER;
#endif
```

3. This [line](https://github.com/oceanbase/miniob/blob/50d3a28bb3e0e235960a580e3148ea00f53c15bf/src/observer/net/buffered_writer.cpp#L16) use the wrong header file as it should be just `errno.h`.

4. `MUSL LIBC` do not have `libexecinfo`, and need to be installed manually. After installation, the `CMakeLists.txt` in `deps/common` need to be added a link option to `libexecinfo`.

5. `MUSL LIBC` has pthread api, but `cmake` may not detect pthread. It requires adding `SET(CMAKE_THREAD_LIBS_INIT "-lpthread")` to the top `CMakeLists.txt`.

6. Missing header file `stdint.h` in `ring_buffer.h`.

After fixing the problems list above, I compiled the project and tested some functions successfully. The first two fixes may not follow your principle of code, so I did not give a PR. I gave an issue so that you can implement the fixes in your style.

Thank you.

**Comment by hnwyllmm** [comment]
Thanks. It's a wonderful job. I think it's OK to push a push request if you'd like to and I'll adapt your code to miniob style.
