### ISSUE TITLE
[BUG] gitpod中缺少Libevent

### ISSUE THREAD

**Issue by liu33333** [oceanbase/miniob#483]
按照Readme运行Gitpod时会报错：
CMake Error at src/observer/CMakeLists.txt:30 (FIND_PACKAGE):
  Could not find a package configuration file provided by "Libevent" with any
  of the following names:

    LibeventConfig.cmake
    libevent-config.cmake

  Add the installation prefix of "Libevent" to CMAKE_PREFIX_PATH or set
  "Libevent_DIR" to a directory containing one of the above files.  If
  "Libevent" provides a separate development package or SDK, be sure it has
  been installed.
  是否是运行环境中没有安装？

**Comment by hnwyllmm** [comment]
请看PR 484，已经修复。
你可以先删除 libevent中的build目录重新构建试试，比如在/workspace/miniob 下执行
```bash
sudo rm -rf deps/3rd/libevent/build deps/3rd/benchmark/build deps/3rd/googletest/build deps/3rd/jsoncpp/build
bash build.sh init
bash build.sh --make -j4
```
