### ISSUE TITLE
undefined reference to `typeinfo for testing::Test'

### ISSUE THREAD

**Issue by typedefstruct32** [oceanbase/miniob#5]
编译完成所有deps后，编译miniob时，报错：
 95%] Built target path_test

[ 95%] Building CXX object unitest/CMakeFiles/md5_test.dir/md5_test.cpp.o

[ 96%] Linking CXX executable ../bin/md5_test

[ 96%] Built target md5_test

[ 96%] Building CXX object unitest/CMakeFiles/log_test.dir/log_test.cpp.o

[ 97%] Linking CXX executable ../bin/log_test

/usr/bin/ld: CMakeFiles/log_test.dir/log_test.cpp.o:(.data.rel.ro._ZTI35checkRotateTest_CheckRoateTest_Test[_ZTI35checkRotateTest_CheckRoateTest_Test]+0x10): undefined reference to `typeinfo for testing::Test'

/usr/bin/ld: CMakeFiles/log_test.dir/log_test.cpp.o:(.data.rel.ro._ZTI35testEnableTest_CheckEnableTest_Test[_ZTI35testEnableTest_CheckEnableTest_Test]+0x10): undefined reference to `typeinfo for testing::Test'

collect2: error: ld returned 1 exit status

make[2]: *** [unitest/CMakeFiles/log_test.dir/build.make:105: bin/log_test] Error 1

make[1]: *** [CMakeFiles/Makefile2:497: unitest/CMakeFiles/log_test.dir/all] Error 2

make: *** [Makefile:149: all] Error 2

**Comment by hnwyllmm** [comment]
同学是不是没有安装googletest

**Comment by zyyue99** [comment]
你好，我遇到了同样的问题，请问你之后是怎么解决的呢？
