### ISSUE TITLE
基本的比如insert,delete操作有问题

### ISSUE THREAD

**Issue by 123liuziming** [oceanbase/miniob#6]
![ecebcf562c8b6cfda843afb03b0f6fc](https://user-images.githubusercontent.com/32130965/139568819-a417b2fa-d282-46ef-b781-2233e715260e.png)
比如我此图，上面的查询是我更改了delete的逻辑，在dispose_page的时候如果把页面删除掉了就让pageCount--，才不会出现delete后select出错的情况。
还有，原生的insert和delete在执行后均不能在磁盘上持久化，miniob的事务代码中并没有此逻辑，并且也没有让我们实现事务的功能。

**Comment by hnwyllmm** [comment]
最新的版本已经没有这个问题，所以关闭。
