### ISSUE TITLE
miniob 在 m1 芯片的 mac 上调试的问题

### ISSUE THREAD

**Issue by Tangruilin** [oceanbase/miniob#64]
想问一下 miniob 应该是还没有适配 m1 的 air 对吧，目前我拉取官方的镜像显示的是只支持 linux/amd64 平台。
<img width="1067" alt="image" src="https://user-images.githubusercontent.com/23651891/188328009-95c4a892-7795-40a3-be27-32d729fbd700.png">

**Comment by hnwyllmm** [comment]
确实没有打arm镜像，后面补上。
可以先用[MiniOB](https://github.com/oceanbase/miniob/blob/main/Dockerfile) 文件本地构建一个

**Comment by Tangruilin** [comment]
好的，麻烦了

**Comment by hnwyllmm** [comment]
docker pull oceanbase/miniob:latest

同学，已经修复，现在可以在m1上面使用了

**Comment by Tangruilin** [comment]
@hnwyllmm 好的，我准备关掉这个 issue 了
