### ISSUE TITLE
'client_performance_test' failed

### ISSUE THREAD

**Issue by matchyc** [oceanbase/miniob#72]
What happened:
In the current version, `client_performance_test.cpp` uses `DEFAULT_PORT` as socket communication port, which is different from '*.ini' file provided by the community in ./etc directory. It leads to `failed to connect` error.
(And guidance commands are not suitable for this, cuz it uses `*.sock` file)

Should we just change the `PORT` used in `client_performance_test.cpp`  to the port set by `.ini` file?

**Comment by hnwyllmm** [comment]
PR is welcomed!
I think command line argument is more convenient and I want to remove the ini file from observer.

**Comment by hnwyllmm** [comment]
fixed
