### ISSUE TITLE
构建镜像的时候下载 cmake 一直会超时

### ISSUE THREAD

**Issue by Tangruilin** [oceanbase/miniob#73]
<img width="1263" alt="image" src="https://user-images.githubusercontent.com/23651891/189195491-3524875a-15b3-43d1-8f05-aba2935b75dc.png">
我这边是直接 wget 拉对应版本的 cmake 的，看样子 ob 这边是把指定版本的 cmake 做成了一个 rpm 包放在 oss 上面了?
不知道这个服务器在哪，我这边本地访问还有使用 github action 访问都是不通的，这个链接是不是要换一下？

**Comment by hnwyllmm** [comment]
正在处理

**Comment by hnwyllmm** [comment]
fixed by https://github.com/oceanbase/miniob/pull/74

**Comment by leauny** [comment]
@Tangruilin 我上次的提交已经修复了这个问题, 你没有同步到最新的内容. 但是我看#74 的修复里又将其删除, yum中安装的cmake版本可能会低于此项目要求的最低版本. 如果#74出现问题可以试试 #65 中的Dockerfile.

**Comment by leauny** [comment]
> @Tangruilin 我上次的提交已经修复了这个问题, 你没有同步到最新的内容. 但是我看#74 的修复里又将其删除, yum中安装的cmake版本可能会低于此项目要求的最低版本. 如果#74出现问题可以试试 #65 中的Dockerfile.

没有看到系统切换到了openanolis, 应该没有问题了

**Comment by Tangruilin** [comment]
@leauny 现在同步了，这个问题现在已经没有了，万分感谢

#74 修复了我说的问题。

**Comment by Tangruilin** [comment]
我准备关闭这个 issue 了
