### ISSUE TITLE
一键安装开发环境的脚本

### ISSUE THREAD

**Issue by hnwyllmm** [oceanbase/miniob#90]
如果不使用docker，希望可以提供一个更小白的，能够可以一键搭建起来开发环境的脚本。

**Comment by sheny1xuan** [comment]
考虑使用cmake的[fetchcontent](https://cmake.org/cmake/help/v3.11/module/FetchContent.html?highlight=fetchcontent_declare)安装gtest,json,libevent的依赖，可以简化编译的流程

**Comment by hnwyllmm** [comment]
fixed by https://github.com/oceanbase/miniob/pull/145
