### ISSUE TITLE
使用docker报错，无法启动server

### ISSUE THREAD

**Issue by Boss-Li12** [oceanbase/miniob#98]
- 使用docker拉取镜像后，执行build.sh
- 启动server后报错，找不到jsoncpp依赖等

**Comment by hnwyllmm** [comment]
可以把你的环境信息贴出来看看，以及执行步骤。
如何进入的容器？是 docker exec -it miniob sh  还是 docker exec -it miniob bash
如果是 sh 的话，换成 bash 试试，miniob 容器中的环境变量使用 .bashrc 设置的

**Comment by hnwyllmm** [comment]
长时间未响应，issue关闭
