### ISSUE TITLE
mac 上使用gcc 12.2编译失败

### ISSUE THREAD

**Issue by liulog** [oceanbase/miniob#99]

**Comment by liulog** [comment]
/Users/liujingyu/miniob/miniob/deps/common/os/path.cpp:194:17: error: 'PATH_MAX' was not declared in this scope
  194 |   char tmp_path[PATH_MAX];
      |                 ^~~~~~~~
/Users/liujingyu/miniob/miniob/deps/common/os/path.cpp:199:14: error: 'tmp_path' was not declared in this scope
  199 |     snprintf(tmp_path, sizeof(tmp_path), "%s/%s", path, entry.d_name);
      |              ^~~~~~~~
make[2]: *** [deps/common/CMakeFiles/common.dir/os/path.cpp.o] Error 1
make[1]: *** [deps/common/CMakeFiles/common.dir/all] Error 2

其中这里的环境是：
cmake3.24.1 
➜  build git:(main) ✗ cat ~/.bashrc
export PATH=/usr/local/Cellar/gcc/12.2.0/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/Cellar/gcc/12.2.0/lib:$LD_LIBRARY_PATH
export CC=/usr/local/Cellar/gcc/12.2.0/bin/gcc-12
export CXX=/usr/local/Cellar/gcc/12.2.0/bin/g++-12

**Comment by liulog** [comment]
偶尔还会出现下面这种错误
      TableMeta::deserialize(std::__1::basic_istream<char, std::__1::char_traits<char> >&) in table_meta.cpp.o
  "Json::Value::asString() const", referenced from:
      TableMeta::deserialize(std::__1::basic_istream<char, std::__1::char_traits<char> >&) in table_meta.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/observer] Error 1
make[1]: *** [src/observer/CMakeFiles/observer.dir/all] Error 2
make: *** [all] Error 2

**Comment by hnwyllmm** [comment]
我在Linux系统上使用12.2的gcc编译测试没有出现这种错误，看起来跟操作系统相关。可以自己定义 PATH_MAX 来修复它，后续会提交代码。
你提到的第二个问题，看起来是连接问题，编译jsoncpp等第三方库的编译器是gcc 12.2吗

**Comment by liulog** [comment]
第二个问题，我也感觉不像使用的gcc，但是我仔细看了一下Cmake编译的信息，里面的COMPILE指向的地址确实是我本地的gcc地址

**Comment by liulog** [comment]
可能是我中间用了 source ~/.bashrc ，就是两种报错不一样，~/.bashrc 里面就是howtobuild中的export 四条，改成自己的

**Comment by CaucherWang** [comment]
是M1芯片吗？

**Comment by liulog** [comment]
mac 20款 的 最后一代 intel 芯片

**Comment by liulog** [comment]
已经准备用docker了

**Comment by hnwyllmm** [comment]
后面有问题再交流，我先关掉了
